---
- hosts: dbnodes
  gather_facts: no
  
  roles:
    - role: spark-setup
      tags: [ never, setup ]
    - role: spark-start
      tags: [ never, start ]
      when: inventory_hostname == ansible_play_hosts[0]
    - role: spark-stop
      tags: [ never, stop ]
      when: inventory_hostname == ansible_play_hosts[0]
