# NOTES
# Make sure you have ssh-forwarding enabled for Ansible:
# dans /etc/ansible/ansible.cfg 
#   -> [ssh_connection]
#      ssh_args=-o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes
# from: https://stackoverflow.com/questions/24124140/ssh-agent-forwarding-with-ansible
#
# Nice ansible debug
# export ANSIBLE_DEBUG=True, export ANSIBLE_LOG_PATH=~/ansible.log, and run playbook with -vvvv

---
# Create reaper_db keyspace
- name: Create reaper_db keyspace
  shell: >
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ansible_ssh_user}}@{{groups['cassandranodes'][0]}}
    {{cassandra_home}}/current_cassandra/bin/cqlsh {{groups['cassandranodes'][0]}} --ssl 
    -e "\"create keyspace if not exists reaper_db 
    with replication={'class' : 'NetworkTopologyStrategy', {{hostvars[groups['cassandranodes'][0]].replication_strategy}} } 
    and durable_writes=true;\""

# Copy shiro.ini
- name: Copy shiro.ini
  copy:
    src: shiro.ini
    dest: "{{ reaper_home }}/shiro.ini"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

# Run docker cassandra-reaper container
- name: Create cassandra-reaper container
  command: >
    docker run 
    -d 
    {{ reaper_net }} 
    -v {{ reaper_home }}/CA/reaper-server-keystore.jks:/etc/ssl/reaper-server-keystore.jks 
    -v {{ reaper_home }}/CA/server-truststore.jks:/etc/ssl/server-truststore.jks
    -v {{ reaper_home }}/shiro.ini:/etc/shiro.ini 
    --name={{ reaper_instance_name }} 
    -e "REAPER_JMX_AUTH_USERNAME={{ cassandra_user }}" 
    -e "REAPER_JMX_AUTH_PASSWORD={{ cassandra_pw }}" 
    -e "REAPER_STORAGE_TYPE=cassandra" 
    -e "REAPER_CASS_CLUSTER_NAME={{ reaper_cluster_name }}" 
    -e "REAPER_CASS_CONTACT_POINTS={{ reaper_contact_points }}" 
    -e "REAPER_CASS_KEYSPACE=reaper_db" 
    -e "REAPER_CASS_ACTIVATE_QUERY_LOGGER=false" 
    -e "REAPER_CASS_AUTH_ENABLED=true" 
    -e "REAPER_CASS_AUTH_USERNAME={{ cassandra_user }}" 
    -e "REAPER_CASS_AUTH_PASSWORD={{ cassandra_pw }}" 
    -e "REAPER_SEGMENT_COUNT=16" 
    -e "REAPER_REPAIR_PARALELLISM=PARALLEL" 
    -e "REAPER_REPAIR_INTENSITY=1.0" 
    -e "REAPER_REPAIR_RUN_THREADS=15" 
    -e "REAPER_ENABLE_CROSS_ORIGIN=true" 
    -e "REAPER_INCREMENTAL_REPAIR=false" 
    -e "REAPER_ENABLE_DYNAMIC_SEED_LIST=true" 
    -e "REAPER_HANGING_REPAIR_TIMEOUT_MINS=30" 
    -e "REAPER_SCHEDULE_DAYS_BETWEEN=3" 
    -e "REAPER_REPAIR_MANAGER_SCHEDULING_INTERVAL_SECONDS=1" 
    -e "REAPER_DATACENTER_AVAILABILITY=ALL" 
    -e "REAPER_AUTO_SCHEDULING_ENABLED=true" 
    -e "REAPER_AUTO_SCHEDULING_INITIAL_DELAY_PERIOD=PT15S" 
    -e "REAPER_AUTO_SCHEDULING_PERIOD_BETWEEN_POLLS=PT10M" 
    -e "REAPER_AUTO_SCHEDULING_TIME_BEFORE_FIRST_SCHEDULE=PT5M" 
    -e "REAPER_AUTO_SCHEDULING_SCHEDULE_SPREAD_PERIOD=PT6H" 
    -e "REAPER_JMX_CONNECTION_TIMEOUT_IN_SECONDS=20" 
    -e "REAPER_USE_ADDRESS_TRANSLATOR=false" 
    -e "REAPER_BLACKLIST_TWCS=false" 
    -e "REAPER_METRICS_ENABLED=false" 
    -e "REAPER_AUTH_USER=opsmaster" 
    -e "REAPER_AUTH_PASSWORD={{ cassandra_opsmaster_pw }}" 
    -e "REAPER_SERVER_APP_PORT={{ reaper_instance_port }}" 
    -e "REAPER_SERVER_ADMIN_PORT={{ reaper_instance_port_s }}" 
    -e "REAPER_CASS_NATIVE_PROTOCOL_SSL_ENCRYPTION_ENABLED=true" 
    -e "JAVA_OPTS=-Dssl.enable=true -Djavax.net.ssl.keyStore=/etc/ssl/reaper-server-keystore.jks -Djavax.net.ssl.keyStorePassword={{cassandra_kt_pw}} -Djavax.net.ssl.trustStore=/etc/ssl/server-truststore.jks -Djavax.net.ssl.trustStorePassword={{cassandra_kt_pw}}"
    {{ reaper_image }}
        