# Stop Spark if running already, run only on master, stops everything
---
  # Check if daemon is alive
  - name: Check if Spark is running
    shell: "ps -ef | grep -i spark | grep -v grep | awk '{print $1}'"
    args:
      chdir: "{{ spark_home }}/current_spark/sbin/"
      executable: /bin/bash
    ignore_errors: yes
    changed_when: false
    register: process_spark_running     
    
  # Kill Spark
  - name: Kill running processes
    shell: "kill {{ item }}"
    args:
      executable: /bin/bash
    with_items: "{{ process_spark_running.stdout_lines }}"
    when: process_spark_running.stdout != ""
    
  # Wait for the process to stop
  - name: Wait for process to really stop
    wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
    with_items: "{{ process_spark_running.stdout_lines }}"
    ignore_errors: yes
    when: process_spark_running.stdout != ""
    