# Stop Cassandra if running already
---
  # Check if daemon is alive
  - name: Check if Cassandra is running
    shell: "ps -p `cat cassandra.pid` --no-headers | awk '{print $1}'"
    args:
      chdir: "{{ cassandra_home }}/current_cassandra/bin/"
      executable: /bin/bash
    ignore_errors: yes
    changed_when: false
    register: process_cassandra_running     
    
  # Kill Cassandra
  - name: Kill running processes
    shell: "kill {{ item }}"
    args:
      executable: /bin/bash
    with_items: "{{ process_cassandra_running.stdout_lines }}"
    when: process_cassandra_running.stdout != ""
    
  # Wait for the process to stop
  - name: Wait for process to really stop
    wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
    with_items: "{{ process_cassandra_running.stdout_lines }}"
    ignore_errors: yes
    when: process_cassandra_running.stdout != ""
    